<h1 style='color:orange;text-align:center'>DAY 1</h1>

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

: 

In [21]:
employeeName = ['gaurav','deepanshu','gourav','harsh']
employeeId = [101,102,103,104]
salary= [45000,55000,66000,12000]

In [26]:
df = pd.DataFrame({'name':employeeName,'employeeId':employeeId,'salary':salary})

In [27]:
df

name  employeeId  salary
0     gaurav         101   45000
1  deepanshu         102   55000
2     gourav         103   66000
3      harsh         104   12000

In [32]:
a = [[3,4,5],[1,2,8]]
d1 = np.array(a)
d1

array([[3, 4, 5],
       [1, 2, 8]])

In [40]:
# make a list of 9 elements and convert that list into 3d array and all the elements are integers
# arr = [[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]]
arr = [[[1,2,3],[4,5,6],[7,8,9]]]

In [41]:
arr

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [37]:
np.ndim(arr)

3

In [57]:
l1 = [1,2,3,4,5,6,7,8,9]
l1 = np.array(l1)
l1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
df1 = np.arange(1,21).reshape(4,5)
df1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [60]:
df1 = pd.DataFrame(data=df1,index=['row1','row2','row3','row4'],columns=['col1','col2','col3','col4','col5'])
df1

col1  col2  col3  col4  col5
row1     1     2     3     4     5
row2     6     7     8     9    10
row3    11    12    13    14    15
row4    16    17    18    19    20

In [61]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [63]:
df = sns.load_dataset("titanic")

In [64]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [70]:
ls1 = ['a','b','c']
password = [1,2,3,4,5,6,7,8,9]
userName = input('enter the name')
userPass = int(input('enter the password'))
if userName in ls1 and userPass in password:
    print("login")
else:
    print("login failed")

login


In [3]:
import tkinter as tk
root = tk.Tk()
root.title('my app')
root.geometry('300x400')
tk.Label(root,text='piet college').pack()
l1 = tk.Label(root,text='username').place(x=40,y=80)
l2 = tk.Label(root,text='password').place(x=40,y=100)
e1 = tk.Entry(root)
e1.place(x=100,y=80)
e2 = tk.Entry(root)
e2.place(x=100,y=100)
b1 = tk.Button(root,text='SUBMIT',bg='yellow').place(x=120,y=130)
root.mainloop()